-- ui/settings_tab.lua
-- Settings collapsible section for the Effect Editor

local M = {}

local config = require("config")
local platform = require("platform")

--------------------------------------------------------------------------------
-- State for text input buffer
--------------------------------------------------------------------------------

local settings_state = {
    data_path = "",
    effect_files_path = "",
    initialized = false,
    status_msg = "",
    status_time = 0
}

--------------------------------------------------------------------------------
-- Initialize buffer from current config
--------------------------------------------------------------------------------

local function init_buffers()
    if settings_state.initialized then return end
    settings_state.data_path = config.DATA_PATH or ""
    settings_state.effect_files_path = config.EFFECT_FILES_PATH or ""
    settings_state.initialized = true
end

--------------------------------------------------------------------------------
-- Save settings to config_user.lua
--------------------------------------------------------------------------------

local function save_config_file()
    if not config.EDITOR_BASE_PATH then
        settings_state.status_msg = "Error: Editor path not set"
        settings_state.status_time = os.clock()
        return false
    end

    local config_path = config.EDITOR_BASE_PATH .. "config_user.lua"
    local win_path = platform.to_win_path(config_path)

    local file = io.open(win_path, "w")
    if not file then
        settings_state.status_msg = "Error: Could not write config file"
        settings_state.status_time = os.clock()
        return false
    end

    file:write("-- config_user.lua\n")
    file:write("-- User configuration for FFT Effect Editor\n")
    file:write("-- Auto-generated by Effect Editor settings\n\n")
    file:write("return {\n")
    file:write(string.format('    DATA_PATH = "%s",\n', settings_state.data_path:gsub("\\", "/")))
    if settings_state.effect_files_path ~= "" then
        file:write(string.format('    EFFECT_FILES_PATH = "%s",\n', settings_state.effect_files_path:gsub("\\", "/")))
    end
    file:write("}\n")
    file:close()

    -- Apply changes to running config
    config.set_data_path(settings_state.data_path)
    config.set_effect_files_path(settings_state.effect_files_path)

    settings_state.status_msg = "Settings saved!"
    settings_state.status_time = os.clock()
    return true
end

--------------------------------------------------------------------------------
-- Reset to defaults
--------------------------------------------------------------------------------

local function reset_to_defaults()
    local appdata = platform.get_appdata_dir()
    settings_state.data_path = appdata .. "/pcsx-effect-editor/"
    settings_state.effect_files_path = ""
    settings_state.status_msg = "Reset to default (not saved yet)"
    settings_state.status_time = os.clock()
end

--------------------------------------------------------------------------------
-- Draw function (as collapsible section)
--------------------------------------------------------------------------------

function M.draw()
    init_buffers()

    -- Not default open (0 = no flags)
    if imgui.CollapsingHeader("Settings") then
        imgui.TextUnformatted("Data Folder (savestates, bins, meta):")
        imgui.SetNextItemWidth(-150)
        local changed, new_val = imgui.extra.InputText("##data_path", settings_state.data_path)
        if changed then
            settings_state.data_path = new_val
        end

        imgui.TextUnformatted("Effect Files (E###.BIN from fft-extract):")
        imgui.SetNextItemWidth(-150)
        local changed2, new_val2 = imgui.extra.InputText("##effect_files_path", settings_state.effect_files_path)
        if changed2 then
            settings_state.effect_files_path = new_val2
        end

        -- Save/Reset buttons
        if imgui.Button("Save", 65, 0) then
            save_config_file()
        end
        imgui.SameLine()
        if imgui.Button("Reset", 65, 0) then
            reset_to_defaults()
        end

        -- Status message (fades after 3 seconds)
        if settings_state.status_msg ~= "" then
            local elapsed = os.clock() - settings_state.status_time
            if elapsed < 3.0 then
                imgui.SameLine()
                imgui.TextUnformatted(settings_state.status_msg)
            else
                settings_state.status_msg = ""
            end
        end
    end
end

return M
